_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
batch_size:
    value: 16
data_path:
    value: /Users/oscargoudet/Desktop/complete_processed_npy
device:
    value: cuda
epochs:
    value: 50
eval:
    value: false
finetune:
    value: /Users/oscargoudet/Desktop/Facade-Autoencoder/chekpoint/mae_pretrain_vit_huge.pth
input_size:
    value: 224
log_dir:
    value: ./output_dir
lr:
    value: 0.001
mask_ratio:
    value: 0.75
num_workers:
    value: 8
output_dir:
    value: ./output_dir
pin_mem:
    value: false
resume:
    value: ""
seed:
    value: 0
start_epoch:
    value: 0
weight_decay:
    value: 0.05
